com/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from com import views

app_name = 'com'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    #url(r'^(?P<name>[\w\-]+)/$',views.viewing_user, name='viewing_user'),
    url(r'^(?P<name>[\w\-]+)/send/$', views.sending_message, name='sending_message'),

]

tellme/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^com/', include('com.urls')),
]

com/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User
from django.utils.encoding import python_2_unicode_compatible

class Profile (models.Model):

    user = models.OneToOneField(User, on_delete = models.CASCADE)
    bio = models.TextField(max_length= 500, blank=True)
    date_of_birth = models.DateField(blank=True, null = True)




class Message (models.Model):
    from_user = models.ForeignKey(User, related_name = 'message_sender')
    to_user = models.ForeignKey(User, related_name = 'messag_receiver')
    content = models.TextField(blank = False)
    date = models.DateTimeField(blank= True)
    def __str__(self):
        return self.content

com/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Profile, Message

class UserForm(forms.ModelForm):

    class Meta:
        Model = User
        fields = ('username','email','password')

class ProfileForm(forms.ModelForm):

    class Meta:
        Model = Profile
        fields = ('bio','date_of_birth')

class MessageForm(forms.ModelForm):
    from_user = forms.IntegerField(widget= forms.HiddenInput(), required = False)
    to_user = forms.IntegerField(widget= forms.HiddenInput(),required = False)
    date = forms.DateTimeField(widget = forms.HiddenInput(),required = False)
    content = forms.CharField(required = True, widget = forms.Textarea)

    class Meta:
        model = Message
        fields = ('from_user', 'to_user','date','content')

com/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from django.contrib.auth.models import User
from .forms import MessageForm
from datetime import datetime
from .models import Message

# Create your views here.
RECEIVER_ID = 0
def index(request):

    try:
        received = Message.objects.filter(to_user =request.user)
    except:
        received = None
    try:
        sent = Message.objects.filter(from_user = request.user)
    except:
        sent = None

    return render(request, 'com/index.html',{'received':received, 'sent': sent})




def sending_message(request, name):
    send_complete = False
    try:
        User_obj = User.objects.get(username = name)
        RECEIVER_ID = User_obj.id
    except User.DoesNotExist:
        User_obj = None


    form = MessageForm()
    if request.method == 'POST':
        form = MessageForm(request.POST)
        if form.is_valid():
            message = form.save(commit = False)
            message.date = datetime.now()
            message.from_user = request.user
            message.to_user = User_obj
            message.save()
            send_complete = True

        else:
            print form.errors
    return render(request, 'com/viewing_user.html', {'form':form, 'u':name,'obj':User_obj, 'state':send_complete})

templates/com/base.html
<!DOCTYPE html>
<html>

<head>

  <title>
    {%block title_block%}
      blaaaaaaaaaaaaaaaaaa
    {%endblock%}
  </title>
</head>

<body>
  {%block body_block%}

  {%endblock%}
  <hr >
<div>
  <ul>
    <li ><a href="{% url 'registration_register'%}"> Register </a> </li>
    {% if user.is_authenticated%}
      <li ><a href="{% url 'auth_logout'%}?next=/com/"> logout </a> </li>
    {%else%}
      <li ><a href="{% url 'auth_login'%}"> login </a> </li>
    {%endif%}

    {{user.}}


  </ul>
</div>
</body>




</html>

templates/com/index.html
{% extends 'com/base.html'%}
<html>

{%block body_block%}
<body>
<h2>Welcome <i>{{user}}</i>, It's TellMe app</h2>

<h3> Received </h3>
{% if received is not None %}
  <ul>
  {%for msg in received%}
    <li> {{msg.content}} </li>
  </ul>
  {%endfor%}
{%endif%}
<h3>Sent</h3>
{% if sent is not None%}
  <ul>
    {%for msg in sent%}
      <li>{{msg.content}}</li>
    {%endfor%}
  </ul>
{%endif%}
</body>
{%endblock%}


</html>

templates/com/viewing_user.html
<html>

  {% if obj == None %}

    <h2>Sorry this user ({{u}}) DoesNotExist</h2>

  {% else %}
    <h3>Be honest, and Tellme what you want</h3>
    <br>
      <i>{{obj.username}}</i>

      <form method="post" enctype= 'multipart/form-data' action="{%url 'com:sending_message' obj.username %}">
        {%csrf_token%}
        {% for hidden in form.hidden_fields%}
          {{hidden}}
        {%endfor%}

        {% for visible in form.visible_fields%}
        {{visible}}
        {%endfor%}

        <input type="submit" value='Tell'/>
      </form>
      {%if state%}
      Thanks for sending {{u}} a message
      {%endif%}

  {%endif%}

</html>